version: '3.9'
services:
    db:
        image: postgres
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
        ports:
          - '5432:5432'
        volumes: 
          # copy the sql script to create tables
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    web:
        build: 
          context: ./QH
        command: npm start
        ports:
          - "3000:3000"
          - "9998:9998"
        depends_on:
          - db
        restart: on-failure
        environment:
          CONNECTION_URL: postgres://postgres:postgres@reti_db_1:5432/postgres
          PORT: 3000
          MAP_KEY: AIzaSyBOpGh2i98vY0tUlDl39xe-CW0gEbK5JPA
          
          
          
          FACEBOOK_CLIENTID: 1132255284295761
          FACEBOOK_CLIENTSECRET: a0374024c74b96b71347593492b7fe69
          FACEBOOK_CALLBACKURL: https://localhost:3000/user/auth/facebook/callback
          
          
          GOOGLE_CLIENTID: 27710775729-j9ivnahb2828ch0ao8ell40r12jr69i2.apps.googleusercontent.com
          GOOGLE_CLIENTSECRET: FTAsu-u5-Y_q-WGh5qNIp3RH
          GOOGLE_CALLBACKURL: https://localhost:3000/user/google/callback