name: Docker-Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v3
    - name: Docker Compose Action
      uses: isbang/compose-action@v1.4.1
    - name: npm installation
      run: npm install
    - name: run test
      run: npm test
