name: Docker-Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: macos-latest
        
    steps:
    - uses: actions/checkout@v3
    - name: Docker Compose Action
      uses: isbang/compose-action@v1.4.1
      

