name: Docker-Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./QH
    steps:
    - uses: actions/checkout@v3
    - name: Docker Compose Action
      uses: isbang/compose-action@v1.4.1
    - name: dove sono
      run: ls
    - name: run test
      run: npm run
